sudo: true

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install cpanminus -y
  - cpanm Template

before_script: 
  - export PATH=`pwd`/bin:$PATH
  - export ZCCCFG=`pwd`/lib/config

script: 
  - make -C src/z80asm test && make && make -C libsrc && make -C libsrc install && make -C libsrc/_DEVELOPMENT && make -C examples && make -C test
