sudo: false

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cpanminus
    - dos2unix
    - liblocal-lib-perl

before_script: 
  - export PATH=`pwd`/bin:$PATH
  - export ZCCCFG=`pwd`/lib/config
  - eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
  - cpanm File::Slurp
  - cpanm Template
  - cpanm Template::Plugin::YAML
  - cpanm Modern::Perl
  - cpanm Test::Differences
  - cpan CPU::Z80::Assembler
#  - cpanm Capture::Tiny
#  - cpanm Capture::Tiny::Extended

script: 
  - make -C src/z80asm test && make && make -C libsrc && make -C libsrc install && make -C libsrc/_DEVELOPMENT && make -C examples && make -C test
